language: minimal
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
script: chmod +x ./mirror-files.sh && ./mirror-files.sh
